### ISSUE TITLE
Version 3.1.0 not available in maven repo

### ISSUE THREAD

**Issue by escay** [eclipse-ee4j/glassfish-shoal#168] opened 2024-01-25 09:37 UTC
When building Glassfish 7.0.12 from master https://github.com/eclipse-ee4j/glassfish/ I get during the build:

```
[INFO] GlassFish ha-shoal-store ........................... FAILURE [  0.261 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  4.878 s
[INFO] Finished at: 2024-01-25T10:29:14+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project ha-shoal-cache-store: Could not res
olve dependencies for project org.glassfish.main.ha:ha-shoal-cache-store:glass
fish-jar:7.0.12-SNAPSHOT: The following artifacts could not be resolved: org.gl
assfish.shoal:shoal-cache:jar:3.1.0 (absent), org.glassfish.main.common:contain
er-common:jar:7.0.12-SNAPSHOT (absent): Could not find artifact org.glassfish
.shoal:shoal-cache:jar:3.1.0 in nexus (http://nexus3:8081/repository/public/) -> [Help 1]
```

I see shoal version 3.1.0 is not available in the maven repo:
https://central.sonatype.com/artifact/org.glassfish.shoal/shoal-cache/versions
causing it to fail being available in local nexus.

Last available version in maven is 3.0.1 while shoal version release is on 3.1.0:
https://github.com/eclipse-ee4j/glassfish-shoal/tree/3.1.0

Expectation: release 3.1.0 is also available in mvn repository.

Workaround: build shoal 3.1.0 local.
```
git clone https://github.com/eclipse-ee4j/glassfish-shoal.git
git checkout new_branch a6ac7f30039999714195b358b474b3a3c4f229c9
mvn clean install
```

**Comment by arjantijms** [comment] 2024-01-25 16:01
For building source code that is from a version that is not released yet, it may be the case that some components are still in staging. You can build in that case with -Pstaging. 

It is time though to release shoal to maven central. I'll do this soon. For now you can try building with -Pstaging if you want.

**Comment by pzygielo** [comment] 2024-01-25 17:21
Duplicate of
- https://github.com/eclipse-ee4j/glassfish/issues/24643

**Closed by pzygielo** 2024-01-25 17:21 UTC
